server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: nhw0926
    password: thdus3182
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 31849756497-ebjd3nuesqimtd0f4v7go4lahkvl771j.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

          facebook:
            client-id: 571833474851804
            client-secret: a66ccb166e0b628c7ed1a62ef3e7daaf
            scope:
              - email
              - public_profile

          naver:
            client-id: aOqXIrkggMy2iDMCsCKO
            client-secret: s1oXbtjQaf
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver # google, facebook은 기본설정이 되어있어 적어줘야한다.

        provider: #naver provider은 기본적으로 등록되어있지않아 내가 등록한다.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 이 주소로 요청하면 naver 창이 뜬다.
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰받기위해 사용
            user-info-uri: https://openapi.naver.com/v1/nid/me  # 프로필 정보 받으려면 호출
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.

